version: '3.8'
services:
    laravel.test: # (o laravel.test)
        build:
            context: .
            dockerfile: Dockerfile
        image: rafh-api
        container_name: rafh-api
        restart: always
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            BROADCAST_CONNECTION: reverb 
        volumes:
            - '.:/var/www/html'
            - ../RAFH-Tecnm/dist:/var/www/frontend
        networks:
            - sail

    reverb:
        build:
            context: .
            dockerfile: Dockerfile
        image: rafh-api
        container_name: rafh-reverb
        restart: always
        command: php artisan reverb:start --host=0.0.0.0 --port=8080
        ports:
            - "8080:8080"
        env_file: .env
        networks:
            - sail

networks:
    sail:
        driver: bridge