server {
    listen 80;
    listen [::]:80;
    server_name _;

    # --- PARTE 1: FRONTEND (VUE) ---
    # location / {
    #     root /var/www/frontend;
    #     index index.html;
    #     try_files $uri $uri/ /index.html;
    # }

    # --- PARTE 2: BACKEND (LARAVEL) ---
    location ~ ^/(api|sanctum|storage|up) {
        root /var/www/html/public;
        try_files $uri $uri/ @laravel;
    }

    # Bloque auxiliar para pasar PHP a Laravel
    location @laravel {
        root /var/www/html/public;
        fastcgi_pass 127.0.0.1:9000;
        # fastcgi_pass unix:/run/php/php8.3-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root/index.php;
        include fastcgi_params;
    }

    # Bloque de seguridad para archivos PHP
    location ~ \.php$ {
        root /var/www/html/public;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

}